config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_fish:
    dst: ~/.config/fish
    src: config/fish
  d_nvim:
    dst: ~/.config/nvim
    src: config/nvim
profiles:
  braxis:
    dotfiles:
    - d_nvim
    - d_fish
